# Generated by Django 2.2.5 on 2019-09-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Experiente'), (3, 'Mestre do inglês')], default=1, null=True, verbose_name='Rank'),
        ),
    ]
