# Generated by Django 2.2.5 on 2019-09-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0002_auto_20190910_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correction',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
    ]
