# Generated by Django 2.2.5 on 2019-09-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0003_auto_20190911_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicacao.Publication', verbose_name='Publicação'),
        ),
    ]
