# Generated by Django 2.2.5 on 2019-09-11 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0005_auto_20190911_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='publication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicacao.Publication', verbose_name='Publicação'),
        ),
    ]
