# Generated by Django 2.2.5 on 2019-09-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0008_remove_correction_corrector'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='coment',
            field=models.TextField(null=True, verbose_name='Comentário'),
        ),
        migrations.DeleteModel(
            name='Correction',
        ),
    ]
