# Generated by Django 2.2.5 on 2019-09-11 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0009_auto_20190911_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='coment',
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.TextField(null=True, verbose_name='Correção')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('corrector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comentarista')),
                ('publications', models.ManyToManyField(to='publicacao.Publication')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
    ]
